services:
  db:
    image: postgres:15
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_order_service
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: inventory_api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/inventory_order_service
      NODE_ENV: development
      PORT: 3000
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run dev
      "

volumes:
  db-data: